### ISSUE TITLE
Restore 'npm run test-for-travis' tests

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-javascript#8]
Restore 'npm run test-for-travis' tests to verify client functionality via headless browser.

**.travis.yml definition**
```yaml
language: node_js
...
services:
- xvfb
script:
- npm run test-for-travis
```
